import type { Metadata } from "next";
import { AI } from './actions';
import { FlyoutNavbar } from "@/components/FlyoutNavbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AI>
      <html lang="en">
        <body className={'bg-background'}>
          {/* <FlyoutNavbar /> */}
          {children}
        </body>
      </html>
    </AI>
  );
}
