import type { Metadata } from "next";
import { AI } from './actions';
import { FlyoutNavbar } from "@/components/FlyoutNavbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: {
    slug: string[];
  };
};

export default function RootLayout({
  children,
  params: { slug },
}: Props) {
  const [id] = slug || []; // Destructure the first part of the slug or fallback to empty array if undefined

  return (
    <AI > {/* Pass the id to AI */}
      <html lang="en">
        <body className={'bg-background'}>
          <FlyoutNavbar />
          <p className="text-black mt-20">{id ? `Slug: ${id}` : "No Slug Found"}</p>
          {children}
        </body>
      </html>
    </AI>
  );
}