import type { Metadata } from "next";
import { AI } from './actions';
import { FlyoutNavbar } from "@/components/FlyoutNavbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: {
    slug: string[];
  };
};

export default function RootLayout({
  children,
  params: { slug },
}: Props) {
  return (
    <AI > 
      <html lang="en">
        <body className={'bg-background'}>
          <FlyoutNavbar />
          {children}
        </body>
      </html>
    </AI>
  );
}